const express = require('express');
const router  = express.Router();
const { getClients, getClient, createClient, updateClient, deleteClient } = require('../controllers/client.controller');
const { protect, adminOnly } = require('../middleware/auth.middleware');
router.use(protect);
router.get('/',              getClients);
router.get('/:id',           getClient);
router.post('/',             createClient);
router.put('/:id',           updateClient);
router.delete('/:id', adminOnly, deleteClient);
module.exports = router;
